name: Lint
description: "Runs Quilt’s lint command on your workspace"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
      name: Checkout

    - uses: actions/setup-node@v2
      name: Setup node.js and yarn
      with:
        node-version: 16.2.0
        cache: yarn

    - name: Yarn install
      run: yarn install --immutable
      shell: bash

    - uses: actions/cache@v2
      id: eslint-cache
      name: Restore ESLint cache
      with:
        path: .sewing-kit/temp/eslint/cache
        key: ${{ runner.os }}-eslint-v1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-eslint-v1-

    - name: Lint
      run: yarn lint
      shell: bash
