name: Lint
description: "Runs Quilt’s lint command on your workspace"
inputs:
  arguments:
    description: "Additional arguments to pass to sewing-kit’s lint command"
    required: false
    default: ""
  command:
    description: "The command to run to start sewing-kit’s lint"
    required: false
    default: "node_modules/.bin/sewing-kit lint"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      id: eslint-cache
      name: Restore ESLint cache
      with:
        path: .sewing-kit/temp/eslint/cache
        key: ${{ runner.os }}-eslint-v1-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-eslint-v1-

    - name: Lint
      run: ${{ inputs.command }} ${{ inputs.arguments }}
      shell: bash
